name: Deploy Laravel

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "abrahamaja/tailadmin-laravel:beta"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug IMAGE_NAME
        run: echo $IMAGE_NAME

      - name: Clean docker
        run: docker system prune -a -f

      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: abrahamaja
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image
        run: docker push $IMAGE_NAME

      - name: Stop container lama
        run: docker rm -f laravel || true

      - name: Run container baru
        run: docker run -d -p 8090:8000 --name laravel $IMAGE_NAME1
